### ISSUE TITLE
add readme and local run instructions

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Islam#34]
Instructions:- 
- should add telegram community link with badge ![https://t.me/islam_app_community](https://img.shields.io/badge/Telegram-3880FF?style=for-the-badge&logoColor=white&logo=telegram)
- Readme template:- https://github.com/othneildrew/Best-README-Template

_Note: You just need to add readme with app's basic logo and screenshots, detailed readme description will be added by maintainers!_

**Comment by sibilrahman** [comment]
I can work on this issue
