### ISSUE TITLE
When switching from landscape mode to portrait, the screen remains half blank

### ISSUE THREAD

**Issue by sibilrahman** [Muhammed-Rahif/Islam#76]
![Screenshot_20230405-075033_Islam.jpg](https://user-images.githubusercontent.com/97382806/229965245-a7220a7b-6a09-4aa0-b8e4-56b21e96301b.jpg)

![Screenshot_20230405-074600_Islam.jpg](https://user-images.githubusercontent.com/97382806/229965246-4cc473f7-7894-4d78-96a8-03526bd9506e.jpg)

**Comment by Muhammed-Rahif** [comment]
Application only work in portscape mode, we need to disable landscape mode.

**Comment by Muhammed-Rahif** [comment]
@sibilrahman want to work on this issue? I think its just have to add two or three words in `android/app/src/main/AndroidManifest.xml` as per the [docs](https://capacitorjs.com/docs/guides/screen-orientation#android-configuration).

Related stackoverflow answer:- https://stackoverflow.com/a/57413087/14781260

**Comment by Muhammed-Rahif** [comment]
resolved on #78
