### ISSUE TITLE
Blank screen when there is no internet.

### ISSUE THREAD

**Issue by sibilrahman** [Muhammed-Rahif/Islam#85]
**Describe the bug**
When I open the application without internet, I see a blank screen.Instead, it would be better to have a No Internet Available icon or text. 

**To Reproduce**
An icon no or a text no that says No internet available would be better.

**Screenshots**
![Screenshot_20230407-141541_Islam.jpg](https://user-images.githubusercontent.com/97382806/230578292-8af655a4-32d5-4cb7-9816-1eca2c43833f.jpg)

**App version:**
1.3.0

**Smartphone :**
 - Samsung M02S
 - Android 12
 - Mobile Application

**Comment by Muhammed-Rahif** [comment]
Making this issue critical because:-
- If the user opening the app for first time and there is no internet, the app's entire screen going blank if any interactions happen.

**Comment by Muhammed-Rahif** [comment]
@sibilrahman any suggetions on this ui?
<img width="360px" src="https://user-images.githubusercontent.com/73386156/230589749-da292af0-6c14-4bff-a5f4-acd54d51e495.png" />

**Comment by sibilrahman** [comment]
@Muhammed-Rahif I think the UI would be a little better if the loading gave a shimmer effect.

**Comment by Muhammed-Rahif** [comment]
> @Muhammed-Rahif I think the UI would be a little better if the loading gave a shimmer effect.

I follow ionic `ios` theme, they don't provide shimmer effect loading. We have to stick with ionic theme to maintain the UI consistency.

> _What is UI consistency?_
> _Consistency in UI design is concerned with making sure elements in a user interface are uniform. They'll look and behave the same way. This helps constantly prove a user's assumptions about the user interface right, creating a sense of control, familiarity, and reliability._

**Comment by Muhammed-Rahif** [comment]
#86
